version: "3.3"

services:

  api:
    build:
      context: .
    image: simple-bank
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - zookeeper
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal

  greeter:
    build:
      context: .
    image: simple-bank
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    depends_on:
      - zookeeper
    networks:
      - internal

  products:
    build:
      context: .
    image: simple-bank
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - mongo
      - zookeeper
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal

  zookeeper:
    image: bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - internal

  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - internal

  traefik:
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
        
  postgres:
    image: postgres:12-alpine
    ports:
      - ${DC_POSTGRES_HOST}:${DC_POSTGRES_HOST_PORT}:${DC_POSTGRES_PORT}
    env_file:
      - .env.postgres
    networks:
      - dev
      - greenatom_atom_core-net    

networks:
  internal:

volumes:
  data:
